import * as dotenv from "dotenv";
dotenv.config({ quiet: true });

export const constants = {
  AUTHENTICATION: {
    PORT: process.env.PORT || 3000,
    DATABASE: {
      URL:
        process.env.DATABASE_URI || "mongodb://localhost:27017/translator-bot",
    },
  },
  URL_VERIFICATION: "url_verification",
  SLACK: {
    CLIENT_ID: process.env.SLACK_CLIENT_ID,
    CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET,
    BOT_TOKEN: process.env.SLACK_BOT_TOKEN,
    SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET,
    BASE_URL: "https://slack.com/api",
    REDIRECT_TO_WORKSPACE: "https://app.slack.com/client/",
  },
  OPENAI: {
    MODEL: "gpt-4o-mini",
    TEMPERATURE: 0,
    MAX_TOKENS: 1000,
    API_KEY: process.env.OPENAI_API_KEY,
  },
  MESSAGES: {
    WELCOME_MESSAGE: `🌍 Welcome to Translator Bot! I can help translate messages in your channels. Use \`/set-translation primary:ja target:en\` to set your language preferences and \`/translate-toggle\` to enable/disable translation in channels.`,
    SET_TRANSLATION_MESSAGE: `👋 Hello! I'm the Translation Bot. Use \`/set-translation primary:ja target:en\` to set your preferences.`,
    ENABLE_TRANSLATION_MESSAGE: `👋 Hello! I'm the Translation Bot. Use \`/set-translation primary:ja target:en\` to set your preferences and \`/translate-toggle\` to enable translation in this channel.`,
  },
  LANGUAGES: {
    af: { name: "Afrikaans", code: "af", flag: "🇿🇦" },
    sq: { name: "Albanian", code: "sq", flag: "🇦🇱" },
    am: { name: "Amharic", code: "am", flag: "🇪🇹" },
    ar: { name: "Arabic", code: "ar", flag: "🇸🇦" },
    hy: { name: "Armenian", code: "hy", flag: "🇦🇲" },
    az: { name: "Azerbaijani", code: "az", flag: "🇦🇿" },
    eu: { name: "Basque", code: "eu", flag: "🇪🇸" },
    be: { name: "Belarusian", code: "be", flag: "🇧🇾" },
    bn: { name: "Bengali", code: "bn", flag: "🇧🇩" },
    bs: { name: "Bosnian", code: "bs", flag: "🇧🇦" },
    bg: { name: "Bulgarian", code: "bg", flag: "🇧🇬" },
    ca: { name: "Catalan", code: "ca", flag: "🇪🇸" },
    ceb: { name: "Cebuano", code: "ceb", flag: "🇵🇭" },
    ny: { name: "Chichewa", code: "ny", flag: "🇲🇼" },
    zh: { name: "Chinese (Simplified)", code: "zh", flag: "🇨🇳" },
    "zh-TW": { name: "Chinese (Traditional)", code: "zh-TW", flag: "🇹🇼" },
    co: { name: "Corsican", code: "co", flag: "🇫🇷" },
    hr: { name: "Croatian", code: "hr", flag: "🇭🇷" },
    cs: { name: "Czech", code: "cs", flag: "🇨🇿" },
    da: { name: "Danish", code: "da", flag: "🇩🇰" },
    nl: { name: "Dutch", code: "nl", flag: "🇳🇱" },
    en: { name: "English", code: "en", flag: "🇺🇸" },
    eo: { name: "Esperanto", code: "eo", flag: "🌍" },
    et: { name: "Estonian", code: "et", flag: "🇪🇪" },
    tl: { name: "Filipino", code: "tl", flag: "🇵🇭" },
    fi: { name: "Finnish", code: "fi", flag: "🇫🇮" },
    fr: { name: "French", code: "fr", flag: "🇫🇷" },
    fy: { name: "Frisian", code: "fy", flag: "🇳🇱" },
    gl: { name: "Galician", code: "gl", flag: "🇪🇸" },
    ka: { name: "Georgian", code: "ka", flag: "🇬🇪" },
    de: { name: "German", code: "de", flag: "🇩🇪" },
    el: { name: "Greek", code: "el", flag: "🇬🇷" },
    gu: { name: "Gujarati", code: "gu", flag: "🇮🇳" },
    ht: { name: "Haitian Creole", code: "ht", flag: "🇭🇹" },
    ha: { name: "Hausa", code: "ha", flag: "🇳🇬" },
    haw: { name: "Hawaiian", code: "haw", flag: "🇺🇸" },
    he: { name: "Hebrew", code: "he", flag: "🇮🇱" },
    hi: { name: "Hindi", code: "hi", flag: "🇮🇳" },
    hmn: { name: "Hmong", code: "hmn", flag: "🇱🇦" },
    hu: { name: "Hungarian", code: "hu", flag: "🇭🇺" },
    is: { name: "Icelandic", code: "is", flag: "🇮🇸" },
    ig: { name: "Igbo", code: "ig", flag: "🇳🇬" },
    id: { name: "Indonesian", code: "id", flag: "🇮🇩" },
    ga: { name: "Irish", code: "ga", flag: "🇮🇪" },
    it: { name: "Italian", code: "it", flag: "🇮🇹" },
    ja: { name: "Japanese", code: "ja", flag: "🇯🇵" },
    jw: { name: "Javanese", code: "jw", flag: "🇮🇩" },
    kn: { name: "Kannada", code: "kn", flag: "🇮🇳" },
    kk: { name: "Kazakh", code: "kk", flag: "🇰🇿" },
    km: { name: "Khmer", code: "km", flag: "🇰🇭" },
    ko: { name: "Korean", code: "ko", flag: "🇰🇷" },
    ku: { name: "Kurdish", code: "ku", flag: "🇮🇶" },
    ky: { name: "Kyrgyz", code: "ky", flag: "🇰🇬" },
    lo: { name: "Lao", code: "lo", flag: "🇱🇦" },
    la: { name: "Latin", code: "la", flag: "🇻🇦" },
    lv: { name: "Latvian", code: "lv", flag: "🇱🇻" },
    lt: { name: "Lithuanian", code: "lt", flag: "🇱🇹" },
    lb: { name: "Luxembourgish", code: "lb", flag: "🇱🇺" },
    mk: { name: "Macedonian", code: "mk", flag: "🇲🇰" },
    mg: { name: "Malagasy", code: "mg", flag: "🇲🇬" },
    ms: { name: "Malay", code: "ms", flag: "🇲🇾" },
    ml: { name: "Malayalam", code: "ml", flag: "🇮🇳" },
    mt: { name: "Maltese", code: "mt", flag: "🇲🇹" },
    mi: { name: "Maori", code: "mi", flag: "🇳🇿" },
    mr: { name: "Marathi", code: "mr", flag: "🇮🇳" },
    mn: { name: "Mongolian", code: "mn", flag: "🇲🇳" },
    my: { name: "Myanmar (Burmese)", code: "my", flag: "🇲🇲" },
    ne: { name: "Nepali", code: "ne", flag: "🇳🇵" },
    no: { name: "Norwegian", code: "no", flag: "🇳🇴" },
    or: { name: "Odia", code: "or", flag: "🇮🇳" },
    ps: { name: "Pashto", code: "ps", flag: "🇦🇫" },
    fa: { name: "Persian", code: "fa", flag: "🇮🇷" },
    pl: { name: "Polish", code: "pl", flag: "🇵🇱" },
    pt: { name: "Portuguese", code: "pt", flag: "🇵🇹" },
    pa: { name: "Punjabi", code: "pa", flag: "🇮🇳" },
    ro: { name: "Romanian", code: "ro", flag: "🇷🇴" },
    ru: { name: "Russian", code: "ru", flag: "🇷🇺" },
    sm: { name: "Samoan", code: "sm", flag: "🇼🇸" },
    gd: { name: "Scots Gaelic", code: "gd", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    sr: { name: "Serbian", code: "sr", flag: "🇷🇸" },
    st: { name: "Sesotho", code: "st", flag: "🇱🇸" },
    sn: { name: "Shona", code: "sn", flag: "🇿🇼" },
    sd: { name: "Sindhi", code: "sd", flag: "🇵🇰" },
    si: { name: "Sinhala", code: "si", flag: "🇱🇰" },
    sk: { name: "Slovak", code: "sk", flag: "🇸🇰" },
    sl: { name: "Slovenian", code: "sl", flag: "🇸🇮" },
    so: { name: "Somali", code: "so", flag: "🇸🇴" },
    es: { name: "Spanish", code: "es", flag: "🇪🇸" },
    su: { name: "Sundanese", code: "su", flag: "🇮🇩" },
    sw: { name: "Swahili", code: "sw", flag: "🇰🇪" },
    sv: { name: "Swedish", code: "sv", flag: "🇸🇪" },
    tg: { name: "Tajik", code: "tg", flag: "🇹🇯" },
    ta: { name: "Tamil", code: "ta", flag: "🇮🇳" },
    tt: { name: "Tatar", code: "tt", flag: "🇷🇺" },
    te: { name: "Telugu", code: "te", flag: "🇮🇳" },
    th: { name: "Thai", code: "th", flag: "🇹🇭" },
    tr: { name: "Turkish", code: "tr", flag: "🇹🇷" },
    tk: { name: "Turkmen", code: "tk", flag: "🇹🇲" },
    uk: { name: "Ukrainian", code: "uk", flag: "🇺🇦" },
    ur: { name: "Urdu", code: "ur", flag: "🇵🇰" },
    ug: { name: "Uyghur", code: "ug", flag: "🇨🇳" },
    uz: { name: "Uzbek", code: "uz", flag: "🇺🇿" },
    vi: { name: "Vietnamese", code: "vi", flag: "🇻🇳" },
    cy: { name: "Welsh", code: "cy", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
    xh: { name: "Xhosa", code: "xh", flag: "🇿🇦" },
    yi: { name: "Yiddish", code: "yi", flag: "🇮🇱" },
    yo: { name: "Yoruba", code: "yo", flag: "🇳🇬" },
    zu: { name: "Zulu", code: "zu", flag: "🇿🇦" },
  },
  LANGUAGE_STYLES: {
    FORMAL: "formal",
    CASUAL: "casual",
  },
};
